/** V2 presentation layer. Reads the generated snapshot; never recomputes risk scores.
 * Current monitoring and historical financial views remain independently dated.
 * All source text is escaped, and source links accept only HTTP(S) protocols.
 */
(()=>{
 if(!D.v2)return;
 const V=D.v2;
 const priorities=['NORMAL','WATCH','ENHANCED MONITORING','CREDIT REVIEW'];
 const paint=x=>['CREDIT REVIEW','SEVERE','CRITICAL','HIGH'].includes(x)?'high':['ENHANCED MONITORING','ELEVATED','WATCH','MODERATE'].includes(x)?'moderate':['NORMAL','LOW','VERY LOW','COMPLETE','CURRENT'].includes(x)?'low':'na';
 const tag=x=>`<span class="pill ${paint(x)}">${esc(x)}</span>`;
 const safeUrl=x=>{try{const u=new URL(x);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
 const sourceLink=(url,label='Source')=>safeUrl(url)?`<a href="${esc(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`:'Source pending';
 const css=document.createElement('style');css.textContent=`.view-tabs{display:flex;gap:8px;margin-bottom:22px}.view-tabs button[aria-selected=true]{background:#14766c;color:#fff;border-color:#14766c}.v2-note{border-left-color:#a36821;background:#fff4df}.v2-grid{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(0,1fr);gap:20px}.v2-alert strong{display:block;margin:4px 0}.v2-alert p{margin:5px 0;color:var(--muted)}.v2-detail h2{margin-bottom:8px}.v2-layers{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:18px 0}.v2-layer{padding:10px;border:1px solid var(--line);border-radius:6px}.v2-layer strong{display:block;font-size:21px;margin:5px 0}.v2-layer small{display:block;font-size:10px;color:var(--muted)}.v2-layer .pill{white-space:normal}.v2-reasons{font-size:12px;color:var(--muted);padding-left:18px}.v2-reasons li{margin:7px 0}.v2-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.v2-detail{overflow-wrap:anywhere}.v2-actions{display:flex;gap:8px;flex-wrap:wrap}#v2-watchlist th button{padding:0;border:0;background:none} @media(max-width:1100px){.v2-grid{grid-template-columns:minmax(0,1fr)}}@media(max-width:500px){.v2-layers{grid-template-columns:1fr}.v2-layer{display:grid;grid-template-columns:1fr auto;align-items:center}.v2-layer small{grid-column:1/-1}.v2-layer strong{margin:0}.view-tabs button{font-size:12px}}@media print{#v2-controls,#v2-cards,#v2-list,.view-tabs,.v2-actions{display:none}.v2-grid{display:block}.v2-detail{border:0}}`;
 document.head.append(css);
 const main=document.querySelector('main');
 const financialView=document.createElement('div');financialView.id='financial-view';
 const original=[...main.children];original.forEach(el=>financialView.append(el));main.append(financialView);
 const tabs=document.createElement('nav');tabs.className='view-tabs';tabs.setAttribute('aria-label','Monitoring views');
 tabs.innerHTML='<button id="tab-watch" aria-selected="true">Current credit watchlist</button><button id="tab-financial" aria-selected="false">Financial history</button>';
 main.prepend(tabs);
 const view=document.createElement('section');view.id='watchlist-view';
 view.innerHTML=`<p class="sub">Monitoring as of <strong>${esc(V.as_of)}</strong>. Financial inputs cover ${esc(D.latest_year)}. Each layer has its own observation date.</p><div class="note v2-note">Financial risk and market stress determine monitoring priority independently. Missing or stale evidence requires follow-up; no blended credit score is calculated.</div><div class="controls" id="v2-controls"><label>Monitoring priority<select id="v2-priority"><option value="">All priorities</option>${priorities.map(p=>`<option>${esc(p)}</option>`).join('')}</select></label><label>Peer universe<select id="v2-group"><option value="">All groups</option>${[...new Set(D.rows.map(r=>r.peer_group))].sort().map(g=>`<option>${esc(g)}</option>`).join('')}</select></label><label>Find counterparty<input id="v2-search" type="search" placeholder="Search company name"></label><label>Sort by<select id="v2-sort"><option value="priority">Priority, then financial risk</option><option value="market">Market stress, highest first</option><option value="name">Company name</option></select></label><button class="push" id="v2-export">Export watchlist CSV</button></div><div class="cards" id="v2-cards" aria-live="polite"></div><div class="v2-grid"><section class="panel" id="v2-list"><h2>Credit watchlist</h2><p class="sub">Priority reflects financial and market observations and data follow-up needs.</p><div class="scroll"><table id="v2-watchlist"><thead><tr><th>Counterparty</th><th>Priority</th><th>Financial</th><th>Market</th></tr></thead><tbody id="v2-table"></tbody></table></div></section><section class="panel v2-detail" id="v2-detail" aria-live="polite"></section></div><details><summary>V2 rules, data coverage and source audit</summary><div id="v2-method"></div></details><footer>Snapshot as of ${esc(V.as_of)}. Refresh prices with the downloader, then run the pipeline. Source audit manifests are saved with the project inputs.</footer>`;
 main.insertBefore(view,financialView);
 document.querySelector('header>h1').textContent='Pharma counterparty credit monitor';
 document.querySelector('header>p').textContent='Financial risk and independent market stress. One explainable monitoring priority.';
 financialView.hidden=true;
 function switchView(watch){view.hidden=!watch;financialView.hidden=watch;$('tab-watch').setAttribute('aria-selected',String(watch));$('tab-financial').setAttribute('aria-selected',String(!watch))}
 $('tab-watch').onclick=()=>switchView(true);$('tab-financial').onclick=()=>switchView(false);
 let chosen=V.watchlist[0]?.company_id,rows=[];
 const groupOf=company=>D.rows.find(r=>r.company_id===company)?.peer_group;
 function draw(){
  rows=V.watchlist.filter(r=>(!$('v2-priority').value||r.monitoring_priority===$('v2-priority').value)&&(!$('v2-group').value||groupOf(r.company_id)===$('v2-group').value)&&r.company_id.toLowerCase().includes($('v2-search').value.toLowerCase()));
  rows.sort((a,b)=>$('v2-sort').value==='name'?a.company_id.localeCompare(b.company_id):$('v2-sort').value==='market'?(b.market_score??-1)-(a.market_score??-1)||a.company_id.localeCompare(b.company_id):b.priority_rank-a.priority_rank||(b.financial_score??-1)-(a.financial_score??-1)||a.company_id.localeCompare(b.company_id));
  const stats=[['Counterparties',rows.length,'In selected filters'],['Priority credit reviews',rows.filter(r=>r.monitoring_priority==='CREDIT REVIEW').length,'Review risk or entity transition'],['Current market coverage',rows.filter(r=>r.market_data_status==='CURRENT').length+'/'+rows.length,'Full market-stress inputs'],['Enhanced monitoring',rows.filter(r=>r.monitoring_priority==='ENHANCED MONITORING').length,'Review triggered financial or market signals']];
  $('v2-cards').innerHTML=stats.map(([l,n,d])=>`<div class="card"><span>${l}</span><strong>${n}</strong><p>${d}</p></div>`).join('');
  if(!rows.some(r=>r.company_id===chosen))chosen=rows[0]?.company_id;
  $('v2-table').innerHTML=rows.map(r=>`<tr data-company="${esc(r.company_id)}" class="${r.company_id===chosen?'selected':''}"><td><button class="table-link">${esc(r.company_id)}</button></td><td>${tag(r.monitoring_priority)}</td><td>${tag(r.financial_rating)}<br>${fmt(r.financial_score)}/100</td><td>${tag(r.market_status)}<br>${r.market_score===null?esc(r.market_data_status):fmt(r.market_score)+'/100'}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No counterparties match the filters.</td></tr>';
  $('v2-table').querySelectorAll('[data-company]').forEach(tr=>tr.querySelector('button').onclick=()=>{chosen=tr.dataset.company;draw()});
  detail();
 }
 function detail(){
  const r=rows.find(r=>r.company_id===chosen);if(!r){$('v2-detail').innerHTML='<p class="empty">No counterparty selected.</p>';return}
  const m=V.market.find(x=>x.company_id===chosen),alerts=V.alerts.filter(x=>x.company_id===chosen);
  const metric=(label,value,p=false)=>`<div class="metric"><span>${label}</span><strong>${fmt(value,p)}</strong></div>`;
  $('v2-detail').innerHTML=`<div class="detail-head"><div><h2>${esc(chosen)}</h2><p class="sub">${esc(groupOf(chosen))}</p></div></div>${tag(r.monitoring_priority)}<div class="v2-layers"><div class="v2-layer"><span>Financial credit risk</span><strong>${fmt(r.financial_score)}<small>/100 · ${esc(r.financial_year)}</small></strong>${tag(r.financial_rating)}<small>${esc(r.financial_data_status)} · Period end ${esc(r.financial_period_end)}</small></div><div class="v2-layer"><span>Market stress</span><strong>${fmt(r.market_score)}<small>/100 · independent signal</small></strong>${tag(r.market_status)}<small>${esc(r.market_data_status)} · ${esc(r.market_date||'No observation')}</small></div></div><h3>Why this priority</h3><ul class="v2-reasons">${r.reasons.split(' | ').map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="note">${esc(r.recommended_action)}</div><p class="sub">${esc(r.confirmation_status)}${r.financial_market_gap_days===null?'':`. Financial/market period gap: ${r.financial_market_gap_days} days.`}</p>${r.entity_event_source?`<p class="sub">Entity transition: ${sourceLink(r.entity_event_source,'Official amalgamation disclosure')}.</p>`:''}<h3>Market signals</h3><p class="sub">${esc(m.ticker)} · ${m.observations} valid sessions · ${sourceLink(m.market_source,'Provider history')}.</p><div class="metrics v2-metrics">${metric('30-session return',m.return_30,true)}${metric('90-session return',m.return_90,true)}${metric('NIFTY Pharma 90-session return',m.benchmark_return_90,true)}${metric('Relative 90-session performance',m.relative_return_90,true)}${metric('Current 30-session drawdown',m.drawdown_30,true)}${metric('Maximum 90-session drawdown',m.maximum_drawdown_90,true)}${metric('Daily volatility, 30 sessions',m.volatility_30_daily,true)}${metric('Volatility spike ratio',m.volatility_ratio)}${metric('Volume spike ratio',m.volume_ratio)}${metric('Annualized volatility',m.volatility_30_annualized,true)}</div>${m.missing_reason?`<p class="sub">Incomplete market inputs: ${esc(m.missing_reason)}.</p>`:''}<h3>Explainable alerts (${alerts.length})</h3>${alerts.map(a=>`<div class="alert v2-alert">${tag(a.severity)} <small>${esc(a.layer)} · ${esc(a.date)}</small><strong>${esc(a.code.replaceAll('_',' '))}</strong><p><b>What:</b> ${esc(a.what_happened)}</p><p><b>Why:</b> ${esc(a.why_it_matters)}</p><p><b>Action:</b> ${esc(a.recommended_action)}</p>${a.source?sourceLink(a.source,'Supporting disclosure'):''}</div>`).join('')||'<p class="sub">No triggered risk rules. Data follow-up may still determine priority.</p>'}<div class="v2-actions" style="margin-top:18px"><button id="v2-print">Print review report</button><button id="v2-history">Open financial history</button></div>`;
  $('v2-print').onclick=()=>window.print();
  $('v2-history').onclick=()=>{$('year').value=r.financial_year;$('group').value='';$('search').value=chosen;selected=chosen;render();switchView(false)};
 }
 function exportCsv(values,fields,name){const cell=x=>'"'+String(x??'').replaceAll('"','""')+'"';const csv=[fields,...values.map(r=>fields.map(k=>r[k]))].map(row=>row.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 $('v2-export').onclick=()=>exportCsv(rows,['company_id','monitoring_as_of','monitoring_priority','financial_score','financial_rating','financial_data_status','market_score','market_status','market_date','market_data_status','confirmed_deterioration','reasons','recommended_action'],'credit_watchlist_'+V.as_of+'.csv');
 for(const id of ['v2-priority','v2-group','v2-sort'])$(id).onchange=draw;$('v2-search').oninput=draw;
 $('v2-method').innerHTML=`<p class="sub">Monitoring model ${esc(V.config.version)}. Market stress weights: relative performance 35, drawdown 30, volatility 20, volume 15. Bounds are configurable proposed rules. A missing component prevents a complete market score.</p><ul class="v2-reasons">${V.config.assumptions.map(a=>`<li>${esc(a)}</li>`).join('')}</ul><h3>Priority rules</h3><p class="sub">Critical financial risk: CREDIT REVIEW. Fresh high financial risk plus elevated/severe market stress: CREDIT REVIEW. Elevated/severe market stress alone: ENHANCED MONITORING. Missing or stale layers: at least WATCH. A documented entity amalgamation requires CREDIT REVIEW for entity/exposure mapping. Market stress never upgrades the primary financial rating.</p><div class="scroll"><table><thead><tr><th>Instrument</th><th>Sessions</th><th>Latest price date</th><th>Age (calendar days)</th></tr></thead><tbody>${V.market_checks.map(r=>`<tr><td>${esc(r.ticker)}</td><td>${r.observations}</td><td>${esc(r.last_date||'Unavailable')}</td><td>${fmt(r.age_calendar_days)}</td></tr>`).join('')}</tbody></table></div>`;
 draw();
})();
